<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TikTok.Analytics.Application\TikTok.Analytics.Application.csproj" />
    <ProjectReference Include="..\TikTok.Analytics.Infrastructure\TikTok.Analytics.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Quartz.AspNetCore" Version="3.13.1" />
  </ItemGroup>

</Project>
